# Upload a file via POST request as multipart/form-data
POST http://localhost:5109/workflows/document-capture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="rechnung10958131.pdf"
Content-Type: application/pdf

< C:/Users/rudi/Documents/Private/steuer/2022/Strom/rechnung10958131.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--
